version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: ToDoApi/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"

    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
